namespace Machete.Parser

type SourceElement =
| PrimaryExpression
| ArrayLiteral
| ElementList
| Elision
| ObjectLiteral
| PropertyNameAndValueList
| PropertyAssignment
| PropertyName
| PropertySetParameterList
| MemberExpression
| NewExpression
| CallExpression
| Arguments
| ArgumentList
| LeftHandSideExpression
| PostfixExpression
| UnaryExpression
| MultiplicativeExpression
| AdditiveExpression
| ShiftExpression
| RelationalExpression
| RelationalExpressionNoIn
| EqualityExpression
| EqualityExpressionNoIn
| BitwiseANDExpression
| BitwiseANDExpressionNoIn
| BitwiseXORExpression
| BitwiseXORExpressionNoIn
| BitwiseORExpression
| BitwiseORExpressionNoIn
| LogicalANDExpression
| LogicalANDExpressionNoIn
| LogicalORExpression
| LogicalORExpressionNoIn
| ConditionalExpression
| ConditionalExpressionNoIn
| AssignmentExpression
| AssignmentExpressionNoIn
| AssignmentOperator
| Expression
| ExpressionNoIn
| Statement
| Block
| StatementList
| VariableStatement
| VariableDeclarationList 
| VariableDeclaration
| Initializer
| EmptyStatement 
| ExpressionStatement
| IfStatement 
| IterationStatement 
| DoWhileStatement
| WhileStatement
| ForStatement
| ForInStatement 
| ContinueStatement
| BreakStatement
| ReturnStatement
| WithStatement
| LabelledStatement 
| SwitchStatement
| CaseBlock 
| CaseClauses 
| CaseClause
| DefaultClause
| ThrowStatement 
| TryStatement 
| Catch
| Finally
| DebuggerStatement
| ForEachStatement
| YieldStatement
| YieldBreakStatement
| YieldContinueStatement
| FunctionDeclaration
| FunctionExpression
| FormalParameterList
| FunctionBody
| Program
| SourceElements
| SourceElement