namespace Machete.Interactive

module Program =
    
    let engine = new Machete.Engine()
    let test () =
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore
        engine.ExecuteScript("Date.now();") |> ignore


    let main () =
        //test();
        //test();
        Interactive.initialize ()

    main()